2021-08-19T12:11:30.333Z [error]: main - uncaughtException: expected { Object (_events, _eventsCount, ...) } to have status code 200 but got 201
AssertionError: expected { Object (_events, _eventsCount, ...) } to have status code 200 but got 201
    at F:\Codes\Node Framework\test\discount.js:16:42
    at Test.Request.callback (F:\Codes\Node Framework\node_modules\superagent\lib\node\index.js:716:12)
    at F:\Codes\Node Framework\node_modules\superagent\lib\node\index.js:916:18
    at IncomingMessage.<anonymous> (F:\Codes\Node Framework\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
2021-08-19T12:13:00.676Z [error]: main - uncaughtException: Cannot read property 'should' of undefined
TypeError: Cannot read property 'should' of undefined
    at F:\Codes\Node Framework\test\discount.js:17:42
    at Test.Request.callback (F:\Codes\Node Framework\node_modules\superagent\lib\node\index.js:716:12)
    at F:\Codes\Node Framework\node_modules\superagent\lib\node\index.js:916:18
    at IncomingMessage.<anonymous> (F:\Codes\Node Framework\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
2021-08-19T12:14:10.761Z [error]: main - uncaughtException: Cannot read property 'should' of undefined
TypeError: Cannot read property 'should' of undefined
    at F:\Codes\Node Framework\test\discount.js:17:42
    at Test.Request.callback (F:\Codes\Node Framework\node_modules\superagent\lib\node\index.js:716:12)
    at F:\Codes\Node Framework\node_modules\superagent\lib\node\index.js:916:18
    at IncomingMessage.<anonymous> (F:\Codes\Node Framework\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
2021-08-19T12:15:13.799Z [error]: main - uncaughtException: expected { Object (accessToken, refreshToken) } to have property 'token'
AssertionError: expected { Object (accessToken, refreshToken) } to have property 'token'
    at F:\Codes\Node Framework\test\discount.js:18:47
    at Test.Request.callback (F:\Codes\Node Framework\node_modules\superagent\lib\node\index.js:716:12)
    at F:\Codes\Node Framework\node_modules\superagent\lib\node\index.js:916:18
    at IncomingMessage.<anonymous> (F:\Codes\Node Framework\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
2021-08-19T12:25:52.028Z [error]: main - uncaughtException: expected {} not to be an object
AssertionError: expected {} not to be an object
    at F:\Codes\Node Framework\test\discount.js:27:49
    at Test.Request.callback (F:\Codes\Node Framework\node_modules\superagent\lib\node\index.js:716:12)
    at IncomingMessage.<anonymous> (F:\Codes\Node Framework\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
2021-08-19T15:58:52.331Z [error]: main - uncaughtException: expected {} to have property 'status'
AssertionError: expected {} to have property 'status'
    at F:\Codes\Node Framework\test\discount.js:43:47
    at Test.Request.callback (F:\Codes\Node Framework\node_modules\superagent\lib\node\index.js:716:12)
    at IncomingMessage.<anonymous> (F:\Codes\Node Framework\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
2021-08-19T16:26:51.375Z [error]: main - uncaughtException: expected {} to equal 'Token Not Found'
AssertionError: expected {} to equal 'Token Not Found'
    at F:\Codes\Node Framework\test\discount.js:43:45
    at Test.Request.callback (F:\Codes\Node Framework\node_modules\superagent\lib\node\index.js:716:12)
    at IncomingMessage.<anonymous> (F:\Codes\Node Framework\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
2021-08-19T16:30:34.489Z [error]: main - uncaughtException: expected { status: 'success', response: 10 } to have property 'success'
AssertionError: expected { status: 'success', response: 10 } to have property 'success'
    at F:\Codes\Node Framework\test\discount.js:63:47
    at Test.Request.callback (F:\Codes\Node Framework\node_modules\superagent\lib\node\index.js:716:12)
    at F:\Codes\Node Framework\node_modules\superagent\lib\node\index.js:916:18
    at IncomingMessage.<anonymous> (F:\Codes\Node Framework\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
2021-08-19T16:33:02.554Z [error]: main - uncaughtException: the given combination of arguments (object and string) is invalid for this assertion. You can use an array, a map, an object, a set, a string, or a weakset instead of a string
AssertionError: the given combination of arguments (object and string) is invalid for this assertion. You can use an array, a map, an object, a set, a string, or a weakset instead of a string
    at F:\Codes\Node Framework\test\discount.js:64:45
    at Test.Request.callback (F:\Codes\Node Framework\node_modules\superagent\lib\node\index.js:716:12)
    at F:\Codes\Node Framework\node_modules\superagent\lib\node\index.js:916:18
    at IncomingMessage.<anonymous> (F:\Codes\Node Framework\node_modules\superagent\lib\node\parsers\json.js:19:7)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
2021-08-19T16:37:52.234Z [error]: main - uncaughtException: expected { Object (_events, _eventsCount, ...) } to not have status code 404
AssertionError: expected { Object (_events, _eventsCount, ...) } to not have status code 404
    at F:\Codes\Node Framework\test\discount.js:35:46
    at Test.Request.callback (F:\Codes\Node Framework\node_modules\superagent\lib\node\index.js:716:12)
    at IncomingMessage.<anonymous> (F:\Codes\Node Framework\node_modules\superagent\lib\node\index.js:916:18)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
